create schema if not exists dbo;

create table dbo."BillingEntityStatus"
(
    "Id" smallint not null
        constraint "PK_BillingEntityStatus"
            primary key,
    "Description" varchar(100) not null
);

insert into dbo."BillingEntityStatus" ("Id", "Description")
values  (0, 'Not active'),
        (1, 'Active');

create table dbo."BillingEntity"
(
    "Id" integer generated by default as identity
        constraint "BillingEntity_PK"
            primary key,
    "Name" varchar(120) not null,
    "BillingName" varchar(120),
    "BillingAddress" varchar(500),
    "VatNumber" varchar(50),
    "SageARCustomerNumber" varchar(12),
    "SageAPVendorNumber" varchar(12),
    "SageIntegratedFrom" date,
    "BillingCycleJson" varchar(1000),
    "Status" smallint not null
        constraint "FK_BillingEntity_BillingEntityStatus"
            references dbo."BillingEntityStatus"
);

create index "IX_BillingEntity_Name"
    on dbo."BillingEntity" ("Name");

create index "IX_BillingEntity_BillingName"
    on dbo."BillingEntity" ("BillingName");

create index "IX_BillingEntity_SageARCustomerNumber"
    on dbo."BillingEntity" ("SageARCustomerNumber");

create index "IX_BillingEntity_SageAPVendorNumber"
    on dbo."BillingEntity" ("SageAPVendorNumber");

create index "IX_BillingEntity_Status"
    on dbo."BillingEntity" ("Status");

create index "IX_BillingEntity_SageIntegratedFrom"
    on dbo."BillingEntity" ("SageIntegratedFrom");

create index "IX_BillingEntity_VatNumber"
    on dbo."BillingEntity" ("VatNumber");
