create table dbo."BillingPeriodBillingStatus"
(
    "Id" smallint not null
        primary key,
    "Name" varchar(50) not null
);

create table dbo."BillingPeriodStage"
(
    "Id" smallint not null
        primary key,
    "Name" varchar(50) not null
);

create table dbo."BillingPeriod"
(
    "Id" bigint generated by default as identity
        constraint "BillingPeriod_pk"
            primary key,
    "BillingEntityId" integer not null
        constraint "FK_BillingPeriod_BillingEntityId"
            references dbo."BillingEntity",
    "PeriodStarting" date not null,
    "PeriodEnding" date not null,
    "Stage" smallint not null
        constraint "FK_BillingPeriod_Stage"
            references dbo."BillingPeriodStage",
    "BillingStatus" smallint not null
        constraint "FK_BillingPeriod_BillingStatus"
            references dbo."BillingPeriodBillingStatus"
        default 0
);

insert into dbo."BillingPeriodBillingStatus" ("Id", "Name")
values  (-1, 'Failed'),
        (0, 'Not processed'),
        (3, 'Completed'),
        (4, 'Processing');

create index "IX_BillingPeriod_BillingEntityIdPeriodEnding"
    on dbo."BillingPeriod" ("BillingEntityId", "PeriodEnding");

create index "IX_BillingPeriod_PeriodEnding"
    on dbo."BillingPeriod" ("PeriodEnding");

create index "IX_BillingPeriod_PeriodStarting"
    on dbo."BillingPeriod" ("PeriodStarting");

create index "IX_BillingPeriod_BillingStatus"
    on dbo."BillingPeriod" ("BillingStatus");

create index "IX_BillingPeriod_Stage"
    on dbo."BillingPeriod" ("Stage");

create table dbo."DataType"
(
    "Id" smallint not null
        primary key,
    "Name" varchar(50) not null
);

insert into dbo."DataType" ("Id", "Name")
values  (0, 'String'),
        (1, 'Guid'),
        (2, 'DateTime'),
        (3, 'DateTimeOffset'),
        (4, 'Int64');

create table dbo."BillingPeriodProperty"
(
    "Id" bigint generated by default as identity
        primary key,
    "BillingPeriodId" bigint not null
        constraint "FK_BillingPeriodProperty_BillingPeriod"
            references dbo."BillingPeriod"
            on delete cascade,
    "PropertyName" varchar(50) not null,
    "DataType" smallint not null
        constraint "FK_BillingPeriodProperty_DataType"
            references dbo."DataType",
    "DataValue" text
);

create unique index "IX_BillingPeriodProperty_BillingPeriodId_PropertyName"
    on dbo."BillingPeriodProperty" ("BillingPeriodId", "PropertyName");

create table dbo."BillingPeriodTaskStatus"
(
    "Id" smallint not null
        constraint "PK_BillingPeriodTaskStatus"
            primary key,
    "Description" varchar(200) not null
);

create table dbo."BillingPeriodTaskType"
(
    "Id" smallint not null
        constraint "PK_BillingPeriodTaskType"
            primary key,
    "Description" varchar(100) not null
);

create table dbo."BillingPeriodTask"
(
    "Id" bigint generated by default as identity
        constraint "PK_BillingPeriodTask"
            primary key,
    "BillingPeriodId" bigint not null
        constraint "FK_BillingPeriodTask_BillingPeriod"
            references dbo."BillingPeriod"
            on delete cascade,
    "TaskType" smallint not null
        constraint "FK_BillingPeriodTask_BillingPeriodTaskType"
            references dbo."BillingPeriodTaskType",
    "Status" smallint not null
        constraint "FK_BillingPeriodTask_BillingPeriodTaskStatus"
            references dbo."BillingPeriodTaskStatus",
    "DependsOn" varchar(1000) not null
        constraint "DF_BillingPeriodTask_DependsOn"
            default '[]',
    "CreatedAt" timestamp with time zone not null,
    "LastAttemptedAt" timestamp with time zone,
    "WaitUntil" timestamp with time zone,
    "Data" text,
    "Stage" smallint not null
        constraint "FK_BillingPeriodTask_Stage"
            references dbo."BillingPeriodStage"
);

create index "IX_BillingPeriodTask_Status"
    on dbo."BillingPeriodTask" ("Status");

create index "IX_BillingPeriodTask_WaitUntil"
    on dbo."BillingPeriodTask" ("WaitUntil");

create index "IX_BillingPeriodTask_Type"
    on dbo."BillingPeriodTask" ("TaskType");

insert into dbo."BillingPeriodTaskStatus" ("Id", "Description")
values  (-2, 'Failed'),
        (-1, 'Failed (to be retried)'),
        (0, 'New'),
        (2, 'Succeeded');

insert into dbo."BillingPeriodStage" ("Id", "Name")
values  (0, 'Period in progress'),
        (20, 'Record billables'),
        (40, 'Post Customer invoice'),
        (50, 'Post vendor bill'),
        (60, 'Settle vendor bill'),
        (100, 'Done');

insert into dbo."BillingPeriodTaskType" ("Id", "Description")
values  (20, 'Refresh Sales Fees and Commission Totals by Billing Code'),
        (40, 'Create EoBP Sage ARCustomerInvoice'),
        (41, 'Post EoBP Sage ARCustomerInvoice'),
        (50, 'Create EoBP Sage APVendorInvoice'),
        (51, 'Post EoBP Sage APVendorInvoice'),
        (60, 'Create EoBP Sage ARCustomerCreditNote'),
        (61, 'Post EoBP Sage ARCustomerCreditNote'),
        (62, 'Create EoBP Sage ARReceiptAndAdjustment'),
        (63, 'Post EoBP Sage ARReceiptAndAdjustment'),
        (64, 'Create EoBP Sage APVendorCreditNote'),
        (65, 'Post EoBP Sage APVendorCreditNote'),
        (66, 'Create EoBP Sage APPaymentAndAdjustment'),
        (67, 'Post EoBP Sage APPaymentAndAdjustment');
